### ISSUE TITLE
More customisation for RedirectUri 

### ISSUE THREAD

**Issue by Ezergil** [thecloudnativewebapp/OidcProxy.Net#110]
Hi! I want to ask to make redirect behaviour more customisable . All logic of RedirectUri creation is incapsulated inside internal RedirectUriFactory and it implements internal interface. So could not be overriden in client's code. There is CustomHostName in BffOptions, but lets assume there are different frontend applications with different urls and they're calling for Bff service and after login we should be redirected to specific frontend application. With current design it is impossible

There are few possible solutions coming to mind :
1) Make IRedirectUriFactory public so client's code could reimplement some custom RedirectUriFactory and register it in DI
2) Instead of CustomHostName there could be some Func<HttpContext, string> GetCustomHostName , so client's code could implement custom logic of choosing hostName depending on e.g. request headers

Thanks in advance!

**Comment by appie2go** [comment]
Hi there,

I've reserved time to work on this project this week. I'll see if i can sqeeze this in.

Cheers,

Thanks for your feedback!

**Comment by Ezergil** [comment]
We have one product divided into few modular monoliths 
Atm we don't think we really need to create multiple clients, so we're planning to use your library in the service that handles authorization via keycloak and proxies requests to all our modular monoliths via yarp. 

So like we have 3 different frontend services (lets say, admin panel, personal area of client and personal area of employee, one API gateway service that handles authorization and proxying requests to specific resource servers 

In facts, this scheme works on deployed versions of applications (because we have ingress configured to serve gateway and fronted on same host) but we've encountered problem connecting local fronted environment to development api gateway, because angular proxy could work with non-localhost domains only with parameter "changeOrigin" set to true. But in this case our gateway service could not understand how to properly create redirectUri back to local frontend

**Comment by appie2go** [comment]
Ah, i see. I'll see if i can open up the IRedirectUriFactory interface and make it public. Currently i'm working on https://github.com/thecloudnativewebapp/GoCloudNative.Bff/issues/80

Next, i'll pick up https://github.com/thecloudnativewebapp/GoCloudNative.Bff/issues/84

Next, i plan to release a 1.0.0rc

I'll see if i can squeeze this in. I hope to complete these issues within this week.

**Comment by Ezergil** [comment]
Thank you!

**Comment by appie2go** [comment]
Hi there,

Just dug into it. I'm not going to make the redirecturlfactory public. That will break the module. That's why it was internal in the first place. However, if i understand your problem correctly, you need to have a feature that enables specifying landingpage per business logic?

I'll work on a solution that makes the following possible:
- I'll implement something that allows specifying the landingpage in a querystring parameter e.g. /account/login?redirect_to=/some/page.html
- I'll implement an interface which allows you to implement business logic to determine where a user should be redirected to.

Let me know if this fits your needs.

Since this is a bit more complicated than i expected, i expect to release it a bit later, the beginning of next week.

Cheers,

**Comment by appie2go** [comment]
Hi there,

Sorry it took some time to get back at your, but you may notice there are quite some changes. Before releaseing the 1.0.0 version of this library we've decided to change a thing or two. You may have noticed we're rebranding from GoCloudNative.Bff to OidcProxy.Net because it's a less opinionated name and it describes the product better (hope you like it)

Everything is available in the package called `OidcProxy.Net` / `OidcProxy.Net.OpenIdConnect` / `OidcProxy.Net.EntraId` / `OidcProxy.Net.Auth0`.

I've just completed work on this issue too, in this answer i will describe the following:

- The recommended approach to complex redirection, using this library
- The difference between a landingpage and a redirect_url, and why these two things (deliberately) have a different name

## How to redirect a user after signing in.

Assume the following situation. There's a web app with an anonymous section, a customer-section, and an admin-section. Also, there's a requirement that customers are redirected to a special birthday page when they sign in on their birthday. Here's how to configure it:

### Configuring the default landingpage

To configure the default landingpage, as you already know, you still configure the landingpage property:

```
{
   ...
   "LandingPage": "/customers.aspx",
   ...
}
```

### Specifying where a customer should land after signing in, on the fly
Now, maybe, your website has a sign-in page with two buttons: 
```html
<button>I am an administrator, sign me in!</button>
<button>I am a customer, sign me in!</button>
```

In that case, you can now specify where the user should be redirected after signing in successfully.  Do however note, that in the upgrade from `GoCloudNative.Bff` to `OidcProxy.Net` there's one very significant breaking change: __the /account endpoint has been renamed to /.auth__  

To specify where a user should go after sign in, use the landingpage querystring paramater, like so:

```html
<a href="/.auth/login?landingpage=/admin">I am an administrator, sign me in!</a>
<a href="/.auth/login?landingpage=/customers">I am a customer, sign me in!</a>
```

This is a feature that can potentially backfire. That's why the landingpage value has a lot of requirements;
- It must be a relative url (user must stay within the domain)
- it must start with a slash, followed by either a number, a digit, or a . 

It may not
- Refer to another domain
- Refer to another protocol
- Execute javascript
- And so forth..

Also, because some find this feature debatable, this feature is disabled by default. Enable it by changing the following setting:

```
{
   ...
   "LandingPage": "/customers.aspx",
   "EnableUserPreferredLandingPages": true,
   ...
}
```

^ this allows the user to choose any value for /.auth/login?landingpage= 

Better would be to whitelist only a few values:
```
{
   ...
   "LandingPage": "/customers.aspx",    
   "AllowedLandingPages": [
      "/admin",
      "/birthday.aspx",
    ],
   ...
}
```

### Implementing custom business rules to determine where user should go after signing in

In the case of redirecting on somebodies birthday, that's still not sufficient. To accomplish that, implement a custom authentication handler:

```csharp
using System.IdentityModel.Tokens.Jwt;
using OidcProxy.Net;

namespace Host.TestApps.Auth0;

public class BirthdayAuthenticationCallbackHandler : DefaultAuthenticationCallbackHandler
{
    public BirthdayAuthenticationCallbackHandler(ILogger<DefaultAuthenticationCallbackHandler> logger) : base(logger)
    {
    }

    public override Task<IResult> OnAuthenticated(HttpContext context, 
        JwtPayload? payload,
        string defaultLandingPage, 
        string? userPreferredLandingPage)
    {
        var birthday = payload
            .Where(claim => claim.Key == "birthday")
            .Select(value =>
            {
                DateTime.TryParse(value.ToString(), out var birthday);
                return birthday;
            })
            .FirstOrDefault();

        IResult landingPage;
        if (birthday.Day == DateTime.Now.Day && birthday.Month == DateTime.Now.Month)
        {
            landingPage = Results.Redirect("birthday.aspx");
        }
        else
        {
            landingPage = Results.Redirect("welcome.aspx");
        }

        return Task.FromResult(landingPage);
    }
}
```

Hook it into the asp.net pipeline like so:

```csharp
builder.Services.AddOidcProxy(config, o =>
{
    o.AddAuthenticationCallbackHandler<BirthdayAuthenticationCallbackHandler>();
});
```

Know that every sign in will go through the authentication callback handler. That includes the requests that have a landingpage specified in the login request (e.g. /.auth/login?landingpage=/admin) The value of this querystring parameter is referred to as the 'user preferred landingpage'.

## Why landingpage != redirect_url
The landingpage is a OidcProxy.Net concept. The redirect_url is an OAuth2/Oidc concept. It's used to exchange a code between the client (the OidcProxy) and the identity provider. This is an essential part of the protocol. The fewer redirect_urls have been configured in your idp, the better.
